// <auto-generated />
using System;
using B2003C4.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace B2003C4.Server.Migrations
{
    [DbContext(typeof(NewsPaperContext))]
    [Migration("20201009065947_B2003C4.Server")]
    partial class B2003C4Server
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("B2003C4.Server.Models.Dokusya", b =>
                {
                    b.Property<double?>("dokuCode")
                        .HasColumnType("REAL");

                    b.Property<string>("addressRyaku")
                        .HasColumnType("TEXT");

                    b.Property<string>("banti")
                        .HasColumnType("TEXT");

                    b.Property<string>("build")
                        .HasColumnType("TEXT");

                    b.Property<string>("junro")
                        .HasColumnType("TEXT");

                    b.Property<double?>("kuiki")
                        .HasColumnType("REAL");

                    b.Property<string>("misebi1")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("tel")
                        .HasColumnType("TEXT");

                    b.HasKey("dokuCode");

                    b.ToTable("Dokusya");
                });

            modelBuilder.Entity("B2003C4.Server.Models.Iri", b =>
                {
                    b.Property<double?>("dokuCode")
                        .HasColumnType("REAL");

                    b.Property<string>("DispNengetu")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GaitoNo")
                        .HasColumnType("REAL");

                    b.Property<string>("IriRiyuu")
                        .HasColumnType("TEXT");

                    b.Property<double?>("KeizokuTuki")
                        .HasColumnType("REAL");

                    b.Property<double?>("MgCode")
                        .HasColumnType("REAL");

                    b.Property<string>("MgNo")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NextKeiyaku")
                        .HasColumnType("REAL");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<string>("build")
                        .HasColumnType("TEXT");

                    b.Property<string>("iri")
                        .HasColumnType("TEXT");

                    b.Property<string>("junro")
                        .HasColumnType("TEXT");

                    b.Property<double?>("kuiki")
                        .HasColumnType("REAL");

                    b.Property<string>("meig")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("nengetu")
                        .HasColumnType("REAL");

                    b.Property<double?>("tantokbn")
                        .HasColumnType("REAL");

                    b.Property<string>("tel")
                        .HasColumnType("TEXT");

                    b.Property<string>("tome")
                        .HasColumnType("TEXT");

                    b.HasKey("dokuCode");

                    b.ToTable("Iri");
                });

            modelBuilder.Entity("B2003C4.Server.Models.Kakuzai", b =>
                {
                    b.Property<double?>("DokuCode")
                        .HasColumnType("REAL");

                    b.Property<double?>("MgCode")
                        .HasColumnType("REAL");

                    b.Property<double?>("SeqNo")
                        .HasColumnType("REAL");

                    b.Property<double?>("Cardryo")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCD1")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCD2")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCD3")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCD4")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCD5")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCD6")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCD7")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCD8")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCD9")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCnt1")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCnt2")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCnt3")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCnt4")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCnt5")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCnt6")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCnt7")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCnt8")
                        .HasColumnType("REAL");

                    b.Property<double?>("HinmeiCnt9")
                        .HasColumnType("REAL");

                    b.Property<string>("HinmeiDate1")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiDate2")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiDate3")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiDate4")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiDate5")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiDate6")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiDate7")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiDate8")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiDate9")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiName1")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiName2")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiName3")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiName4")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiName5")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiName6")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiName7")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiName8")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinmeiName9")
                        .HasColumnType("TEXT");

                    b.Property<double?>("KansaCd")
                        .HasColumnType("REAL");

                    b.Property<string>("KansaName")
                        .HasColumnType("TEXT");

                    b.Property<double?>("KetteisyaCD")
                        .HasColumnType("REAL");

                    b.Property<string>("KetteisyaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MgNo")
                        .HasColumnType("TEXT");

                    b.HasKey("DokuCode", "MgCode", "SeqNo");

                    b.ToTable("Kakuzai");
                });

            modelBuilder.Entity("B2003C4.Server.Models.Koudoku", b =>
                {
                    b.Property<double?>("DokuCode")
                        .HasColumnType("REAL");

                    b.Property<double?>("OyaMgCode")
                        .HasColumnType("REAL");

                    b.Property<string>("MgNo")
                        .HasColumnType("TEXT");

                    b.Property<double?>("No")
                        .HasColumnType("REAL");

                    b.Property<double?>("MgCode")
                        .HasColumnType("REAL");

                    b.Property<string>("IriRiyuu")
                        .HasColumnType("TEXT");

                    b.Property<double?>("KakuzaiNo")
                        .HasColumnType("REAL");

                    b.Property<string>("KeiyakuDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeiyakuEd")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeiyakuKbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeiyakuSt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keiyakusya")
                        .HasColumnType("TEXT");

                    b.Property<string>("MgFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MgName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TomeDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("TomeRiyuu")
                        .HasColumnType("TEXT");

                    b.Property<double?>("haitatubi")
                        .HasColumnType("REAL");

                    b.Property<double?>("tukisu")
                        .HasColumnType("REAL");

                    b.HasKey("DokuCode", "OyaMgCode", "MgNo", "No", "MgCode");

                    b.ToTable("Koudoku");
                });

            modelBuilder.Entity("B2003C4.Server.Models.Kuiki", b =>
                {
                    b.Property<double?>("kuiki")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("kuiki");

                    b.ToTable("Kuiki");
                });

            modelBuilder.Entity("B2003C4.Server.Models.Nengetu", b =>
                {
                    b.Property<double?>("no")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("nengetu")
                        .HasColumnType("REAL");

                    b.HasKey("no");

                    b.ToTable("Nengetu");
                });

            modelBuilder.Entity("B2003C4.Server.Models.Setting", b =>
                {
                    b.Property<string>("KeyMobileNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("FtpIp")
                        .HasColumnType("TEXT");

                    b.Property<double>("LicenseCount")
                        .HasColumnType("REAL");

                    b.Property<double>("MobileCount")
                        .HasColumnType("REAL");

                    b.Property<string>("MobilePw")
                        .HasColumnType("TEXT");

                    b.HasKey("KeyMobileNo");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("B2003C4.Server.Models.TakeOutCount", b =>
                {
                    b.Property<string>("Idx")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileCnt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyoriYMD")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidTerm")
                        .HasColumnType("TEXT");

                    b.HasKey("Idx");

                    b.ToTable("TakeOutCount");
                });

            modelBuilder.Entity("B2003C4.Server.Models.Tome", b =>
                {
                    b.Property<double?>("dokuCode")
                        .HasColumnType("REAL");

                    b.Property<string>("DispNengetu")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GaitoNo")
                        .HasColumnType("REAL");

                    b.Property<string>("IriRiyuu")
                        .HasColumnType("TEXT");

                    b.Property<double?>("KeizokuTuki")
                        .HasColumnType("REAL");

                    b.Property<double?>("MgCode")
                        .HasColumnType("REAL");

                    b.Property<string>("MgNo")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NextKeiyaku")
                        .HasColumnType("REAL");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<string>("build")
                        .HasColumnType("TEXT");

                    b.Property<string>("iri")
                        .HasColumnType("TEXT");

                    b.Property<string>("junro")
                        .HasColumnType("TEXT");

                    b.Property<double?>("kuiki")
                        .HasColumnType("REAL");

                    b.Property<string>("meig")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("nengetu")
                        .HasColumnType("REAL");

                    b.Property<double?>("tantokbn")
                        .HasColumnType("REAL");

                    b.Property<string>("tel")
                        .HasColumnType("TEXT");

                    b.Property<string>("tome")
                        .HasColumnType("TEXT");

                    b.HasKey("dokuCode");

                    b.ToTable("Tome");
                });
#pragma warning restore 612, 618
        }
    }
}
